// The 24 Damage heroes supported by the deployed recommendation artifact.
// IDs must match exactly what the API expects (data/rank_stats.csv hero_id).
const DAMAGE_HEROES = [
  { id: "anran", name: "Anran" },
  { id: "ashe", name: "Ashe" },
  { id: "bastion", name: "Bastion" },
  { id: "cassidy", name: "Cassidy" },
  { id: "echo", name: "Echo" },
  { id: "emre", name: "Emre" },
  { id: "freja", name: "Freja" },
  { id: "genji", name: "Genji" },
  { id: "hanzo", name: "Hanzo" },
  { id: "junkrat", name: "Junkrat" },
  { id: "mei", name: "Mei" },
  { id: "pharah", name: "Pharah" },
  { id: "reaper", name: "Reaper" },
  { id: "shion", name: "Shion" },
  { id: "sierra", name: "Sierra" },
  { id: "sojourn", name: "Sojourn" },
  { id: "soldier-76", name: "Soldier: 76" },
  { id: "sombra", name: "Sombra" },
  { id: "symmetra", name: "Symmetra" },
  { id: "torbjorn", name: "Torbjörn" },
  { id: "tracer", name: "Tracer" },
  { id: "vendetta", name: "Vendetta" },
  { id: "venture", name: "Venture" },
  { id: "widowmaker", name: "Widowmaker" },
];

// Matchup opponent lists can include any of the 53 heroes (Tank/Support
// opponents, not just Damage), so this map covers the full roster for
// display purposes. The dropdowns above still only ever offer the 24
// Damage heroes.
const ALL_HERO_NAMES = {
  ana: "Ana",
  anran: "Anran",
  ashe: "Ashe",
  baptiste: "Baptiste",
  bastion: "Bastion",
  brigitte: "Brigitte",
  cassidy: "Cassidy",
  dmon: "D.Mon",
  domina: "Domina",
  doomfist: "Doomfist",
  dva: "D.Va",
  echo: "Echo",
  emre: "Emre",
  freja: "Freja",
  genji: "Genji",
  hanzo: "Hanzo",
  hazard: "Hazard",
  illari: "Illari",
  "jetpack-cat": "Jetpack Cat",
  "junker-queen": "Junker Queen",
  junkrat: "Junkrat",
  juno: "Juno",
  kiriko: "Kiriko",
  lifeweaver: "Lifeweaver",
  lucio: "Lúcio",
  mauga: "Mauga",
  mei: "Mei",
  mercy: "Mercy",
  mizuki: "Mizuki",
  moira: "Moira",
  orisa: "Orisa",
  pharah: "Pharah",
  ramattra: "Ramattra",
  reaper: "Reaper",
  reinhardt: "Reinhardt",
  roadhog: "Roadhog",
  shion: "Shion",
  sierra: "Sierra",
  sigma: "Sigma",
  sojourn: "Sojourn",
  "soldier-76": "Soldier: 76",
  sombra: "Sombra",
  symmetra: "Symmetra",
  torbjorn: "Torbjörn",
  tracer: "Tracer",
  vendetta: "Vendetta",
  venture: "Venture",
  widowmaker: "Widowmaker",
  winston: "Winston",
  "wrecking-ball": "Wrecking Ball",
  wuyang: "Wuyang",
  zarya: "Zarya",
  zenyatta: "Zenyatta",
};

function heroName(id) {
  return ALL_HERO_NAMES[id] || id;
}
